server:
  port: 8082
spring:
  application.name: pcalculator
  datasource:
    url: jdbc:mysql://localhost:3306/pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 10RelationalDatabasesAreVeryUseful!
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
