name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feat/position_history ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better code quality analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: ./mvnw -B clean verify

      - name: Run Tests
        run: ./mvnw test

      - name: Generate JaCoCo Report
        run: ./mvnw jacoco:report

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: target/surefire-reports/**/*.xml

      - name: Check code coverage
        id: jacoco
        run: |
          COVERAGE=$(grep -oP '(?<=<total>).*(?=</total>)' target/site/jacoco/jacoco.xml | grep -oP '(?<=covered percent=").*(?=")')
          echo "Code coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "::warning ::Code coverage is below 80%. Current coverage: $COVERAGE%"
          fi

      - name: Check dependency vulnerabilities
        run: ./mvnw dependency-check:check

      - name: CheckStyle
        run: ./mvnw checkstyle:check

      - name: SpotBugs
        run: ./mvnw spotbugs:check

      - name: Build package
        run: ./mvnw -B package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 5